openapi: "3.0.3"
info:
  title: "Logistic API"
  description: "Logistic API"
  version: "1.0.0"
servers:
  - url: "https://Logistic"
tags:
  - name: Users
    description: Endpoints referidos a la interacción con usuarios
paths:
  /user/{id}:
    get:
      tags:
        - Users
      summary: "Obtener un usuario usando el id"
      operationId: "getById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "OK"

  /user/save:
    post:
      tags:
        - Users
      summary: "Salvar un usuario"
      operationId: "save"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserModel"
        required: true
      responses:
        "200":
          description: "OK"
  /user:
    get:
      tags:
        - Users
      summary: "Obtener todos los usuarios"
      operationId: "getAll"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/UserModel"
components:
  schemas:
    UserModel:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        email:
          type: "string"